### ISSUE TITLE
Sample CSV file missing

### ISSUE THREAD

**Issue by JakobGSvendsen** [Azure/azure-docs-powershell-samples#200]
Sample CSV link is broken in

https://github.com/Azure/azure-docs-powershell-samples/tree/master/azure-migrate/migrate-at-scale-with-site-recovery

The Ssample CSv is required for us to know how to fill in the CSV template.

**Comment by sdwheeler** [comment]
@ediazrod @luisjfdez @gontxu7 @snehaamicrosoft  Can one of you provide the missing CSV file that is referenced in this sample?

**Comment by ediazrod** [comment]
Yes I will try

**Comment by ediazrod** [comment]
You can find this script or example here.

https://github.com/ljfernan/AsrReplication

**Comment by ediazrod** [comment]
Please Close

**Comment by sdwheeler** [comment]
@ediazrod The version of the content in this repo links to two CSV files. 

- Input CSV template
- Sample CSV

But the link to Sample CSV is broken. This the file missing or is the link improper?

**Comment by mikefrobbins** [comment]
Closing issue due to age and lack of responses. Please reopen if this is still an outstanding issue.
