### ISSUE TITLE
Startup order ?

### ISSUE THREAD

**Issue by mlubansk** [Azure/azure-docs-powershell-samples#201]
In asr_testmigration.ps1 and asr_migration.ps1, do the servers start in the same order that they are listed in the CSV file ?

**Comment by sdwheeler** [comment]
@ediazrod @luisjfdez @gontxu7 @snehaamicrosoft Can one of you answer this question?

**Comment by mikefrobbins** [comment]
Closing issue due to age and lack of responses. Please reopen if this is still an outstanding issue.
