### ISSUE TITLE
Az.RecoveryServices PS Module v2.4 - Changes Required

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-docs-powershell-samples#253]
Hello

Please note that command New-AzRecoveryServicesAsrReplicationProtectedItem has been updated with new parameters in Az.RecoveryServices module v2.4
https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/new-azrecoveryservicesasrreplicationprotecteditem?view=azps-3.3.0#parameters

Specifically target storage account has been replaced by Disk Type parameter.

Please modify csv file and asr_startmigration.ps1 to address same.

Thanks
Ajay

**Comment by mikefrobbins** [comment]
I've assigned this issue to the author of the script.
