### ISSUE TITLE
PositionalParameterNotFound error while creating VNET using PowerShell

### ISSUE THREAD

**Issue by kudlatiger** [Azure/azure-docs-powershell-samples#286]
I was trying one of the sample from repo and getting below error. 

    #========Create a virtual network with a front-end subnet and back-end subnet.======================
    try {

         # Create a virtual network with a front-end subnet and back-end subnet.
           $fesubnet = New-AzVirtualNetworkSubnetConfig -Name $FrontendSubnet -AddressPrefix '10.0.1.0/28'
           $besubnet = New-AzVirtualNetworkSubnetConfig -Name $BackendSubnet -AddressPrefix '10.0.2.0/28'
           $stmsubnet = New-AzVirtualNetworkSubnetConfig -Name $FunctionSubnet -AddressPrefix '10.0.3.0/28'

            $vnet = New-AzVirtualNetwork -ResourceGroupName $rgName -Name $virtualNetworkName -AddressPrefix '10.0.0.0/26' `
        -Location $location -Subnet $stmsubnet $fesubnet, $besubnet

     }
     catch {
          Write-Host "Failed to create VNET!"
          exit
     }

I am getting below error

System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument 'System.Object[]'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by mikefrobbins** [comment]
@kudlatiger Could you provide a link to the script that you experienced this issue with?

**Comment by kudlatiger** [comment]
Here we go @mikefrobbins 

https://github.com/Azure/azure-docs-powershell-samples/blob/master/virtual-network/virtual-network-multi-tier-application/virtual-network-multi-tier-application.ps1

**Comment by mikefrobbins** [comment]
@kudlatiger Can you confirm that this line is correct in your example. There appears to be a comma missing after `$stmsubnet` or maybe the last two variables need to be removed.

`New-AzVirtualNetwork -ResourceGroupName $rgName -Name $virtualNetworkName -AddressPrefix '10.0.0.0/26' -Location $location -Subnet $stmsubnet $fesubnet, $besubnet`

**Comment by mikefrobbins** [comment]
@kudlatiger Closing this issue since it's been 10 days with no response. If you're still experiencing problems, let us know and we'll reopen this issue.
