### ISSUE TITLE
Import Module failed (AzureMigrateAssessmentCreationUtility.psm1)

### ISSUE THREAD

**Issue by frehnejc** [Azure/azure-docs-powershell-samples#305]
`The command name 'New-Group-Add-Machines' from the module 'AzureMigrateAssessmentCreationUtility' contains one or more of the following restricted characters: # , ( ) { } [ ] & - / \ $ ^ ; : " ' < > | ? @ ` * % + = ~`

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mikefrobbins** [comment]
@frehnejc Can you provide us with a link to the referenced sample script?

**Comment by frehnejc** [comment]
This one:
azure-migrate/assessment-utility/AzureMigrateAssessmentCreationUtility.psm1

**Comment by mikefrobbins** [comment]
@frehnejc I'm reaching out to @weeyin83  who is the author of the referenced script to have them take a look at it.

**Comment by weeyin83** [comment]
@mikefrobbins, I am not the author of this script. 

@frehnejc, although you get that error message can you still use the commands that are being loaded? Or does it fail completely??

**Comment by frehnejc** [comment]
It fails completely.

**Comment by mikefrobbins** [comment]
@weeyin83 my apologies.

@frehnejc Can you run `$DebugPreference = 'Continue'` prior to running the command that fails to see if any additional details are provided? You'll need to set `$DebugPreference = 'SilentlyContinue'` or restart your PowerShell session afterwards.

**Comment by artisticcheese** [comment]
It's just a warning for me and allows to import a module. It does not fail. It's due to the fact that several `-` dash signed as used in cmdlet name I assume.

**Comment by mikefrobbins** [comment]
@frehnejc, @artisticcheese is correct, this is just a warning due to the author not using Verb-Noun for the function names that are being exported by the module. You can safely use the following command to suppress this warning:

`Import-Module <file path>\AzureMigrateAssessmentCreationUtility.psm1 -DisableNameChecking`

I'm reaching out to the Azure Migrate service team for a permanent solution. Either to change the `New-Group-Add-Machines` function to private or to rename it using the appropriate Verb-Noun naming convention.

**Comment by rashi-ms** [comment]
@mikefrobbins Created the PR #315 and PR #316 to resolve this issue
