### ISSUE TITLE
PowerBI Template does not handle multiple database instances on one VM

### ISSUE THREAD

**Issue by frehnejc** [Azure/azure-docs-powershell-samples#308]
PowerBI Throws error for template "Azure Migrate Assessment Comparison PowerBI Template.pbit":
Column 'MachinesName in Table 'CentralSQLServer' contains a duplicate value 'Server01' and this is not allowed for columns on the one side of a many-to-one relationship of for columns that are used as the primary key of a table.

**Comment by mikefrobbins** [comment]
@frehnejc Can you provide us with a link to the referenced sample script?

**Comment by frehnejc** [comment]
This one:
azure-migrate/assessment-utility/Azure Migrate Assessment Comparison PowerBI Template.pbit

**Comment by mikefrobbins** [comment]
@frehnejc I'm reaching out to @rashi-ms who is the author of the referenced template to have them take a look at it.

**Comment by rashi-ms** [comment]
Tagging @shikhersaluja for the resolution.

**Comment by rashi-ms** [comment]
@mikefrobbins - Can you please change the owner of this issue to @shikhersaluja . I have already communicated the issue to him and we will commit the fix once done.

**Comment by shikhersaluja** [comment]
@mikefrobbins, @frehnejc: This issue should be resolvable by removing MachineName as one of the Primary Keys that links tables/ queries in PowerBI. To do so, please go to the "Model" tab either in the template before adding any data or after adding "all" the desired Excel workbooks/ CSVs to the PBIT, and then remove the "MachineName" relationship on the "CentralSQLServer" table.

I am assuming that you are adding all the excel workbooks/ CSVs in one go. As mentioned in our documentation, the PBIT doesn't support update to an already populated "PBIX". Whenever, you want to add new data to the Dashboard you must start from the beginning ie add all the data including the updates (if you may encounter this error when you are not doing so as well).

**Comment by mikefrobbins** [comment]
Closing this issue based on @shikhersaluja's response. @frehnejc, if you are still experiencing problems, let us know and we'll reopen this issue.
