### ISSUE TITLE
Token Usage Not Working

### ISSUE THREAD

**Issue by justinhulsman** [Azure/azure-docs-powershell-samples#323]
Line 20:  $CurrentContext = Get-AzContext

"Get-AzContext" seems to not include token...

Line 47: $TokenCache = $CurrentContext.TokenCache 

TokenCache is not a valid attribute...  Execution throws the following:

Missing or incomaptible module version. Get the latest version of the Az.Accounts module
At C:\Users\100031355\Documents\WindowsPowerShell\azure-docs-powershell-samples-master\azure-migrate\dependencies-at-scale\AzMig_Dependencies.psm1:49 char:9
    +         throw "Missing or incomaptible module version. Get the latest ...
    +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Missing or inco...Accounts module:String) [], RuntimeException
    + FullyQualifiedErrorId : Missing or incomaptible module version. Get the latest version of the Az.Accounts module

**Comment by mikefrobbins** [comment]
@justinhulsman Can you provide the version of the **Az.Accounts** PowerShell module you're running?

The following command can be used to determine the version: `Get-Module -Name Az.Accounts`

**Comment by justinhulsman** [comment]
@mikefrobbins Thanks for getting back with me.

I'm running 2.2.4.

PS C:\Windows\system32> Get-InstalledModule -Name Az.Accounts

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.2.4                Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....

**Comment by mikefrobbins** [comment]
@justinhulsman This issue should now be resolved based on PR #320.

I'm going to proceed with closing this issue, but let us know if you continue to experience issues and we'll reopen it.
