### ISSUE TITLE
This PS does not work for me and found 2 bugs in it

### ISSUE THREAD

**Issue by AzAmitShah** [Azure/azure-docs-powershell-samples#339]
i am having 2 appliances installed and i am using Southeast Asia as a region

1. applianceNameToSiteIdMapV2 does not work, i changed it to applianceNameToSiteIdMapV3 and its working fine for me.
2. foreach does not fetch the appliance SiteId though $sites do have appliances listed because we cant get $site,ApplianceName directly as the key itself is appliance name that has to be passed. i don't know how to dynamically fetch the appliance name hence need help to solve this. 

	$sites = ConvertFrom-Json $siteresponse.properties.details.extendedDetails.applianceNameToSiteIdMapV3
	
	$VMwareSiteID = ""
	
	foreach ($site in $sites) {
	
		$appliancename = $site.ApplianceName;
		
		if ($Appliance -ne $appliancename) {continue}
	
		$VMwareSiteID =  $site.SiteId

	}

**Comment by mikefrobbins** [comment]
@AzAmitShah Please provide a link to the script that you're experiencing issues with.

**Comment by mikefrobbins** [comment]
@AzAmitShah If this is still an outstanding issue, please provide the requested information. Due to the age of this issue, it will be closed in two business days if we have not heard back from you.

**Comment by mikefrobbins** [comment]
Closing due to age of issue and no response in the past 30 days when requesting additional information.
