### ISSUE TITLE
Ability to migrate to a different subscription

### ISSUE THREAD

**Issue by dineshazure** [Azure/azure-docs-powershell-samples#345]
Hi I think VMWare agentless Powershell scripts needs to be added with ability to migrate to a different subscription. Azure Migrate module provides option to migrate servers to different subscription rather than using same subscription where Azure migrate project is created. I have modified it script locally and it looks fine except for the availability set.

**Comment by nelsd** [comment]
@mikefrobbins, @rahug1190, @anvar-ms I have updated the code, csv file and readme file to accommodate this use case. PR - #355 . We missed this use case when we originally came up with these scripts.
@dineshazure - FYI, you could try this after this has merged successfully.

**Comment by mikefrobbins** [comment]
@dineshazure, @nelsd has resolved this issue in PR #355.
