### ISSUE TITLE
Creation of $secpassw for ACR Service Principal fails after migration to MicrosoftGraph API

### ISSUE THREAD

**Issue by fillip1983** [Azure/azure-docs-powershell-samples#363]
The below line is used to generate a secure password which is passed to `New-AzADServicePrincipal`

`$secpassw = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential -Property @{ StartDate=Get-Date; EndDate=Get-Date -Year 2024; Password=$password}`

When  attempting to do this with version 7.1 of the Az Modules, you receive the following error:

> New-Object: Cannot find type [Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential]: verify that the assembly containing this type is loaded

Which according to this issue: https://github.com/Azure/azure-powershell/issues/16671, relates to the shift to MicrosoftGraph API with newer Az PowerShell modules. 
The sample needs updating to reflect this and an alternate approach

**Comment by fillip1983** [comment]
In addition, any references to `ApplicationId `are now likely to be `AppId` instead.

**Comment by mikefrobbins** [comment]
@fillip1983 Which sample is this for?

**Comment by fillip1983** [comment]
> @fillip1983 Which sample is this for?

Apologies. It’s for the creation of a Service Principal for use with an ACR:

https://github.com/Azure/azure-docs-powershell-samples/blob/master/container-registry/service-principal-create/service-principal-create.ps1
