### ISSUE TITLE
AzMigrate-StartReplication.ps1 cannot find Availability Set if in different subscription than Azmigrate (Target sub)

### ISSUE THREAD

**Issue by jasonrfritz3c** [Azure/azure-docs-powershell-samples#365]
The "AzMigrate-StartReplication.ps1" script was failing for me with the following error due to fact that the Availability Set I was trying to assign to some VMs I was initiating replication for was in a different subscription than the AzMigrate appliance/project - i.e. the TARGET sub that the VMs were to live:

20220308_141933[ERROR]-Get-AzAvailabilitySet : Resource group 'AS-RGNAME' could not be found.
ErrorCode: ResourceGroupNotFound
ErrorMessage: Resource group 'AS-RGNAME' could not be found.
ErrorTarget: 
StatusCode: 404
ReasonPhrase: Not Found
OperationID : d15c666c-e04b-4742-ad45-58dc6e35d4f8
At C:\Users\PATH\Azure-Migrate\Agentless VMware automation\AzMigrate_StartReplication.ps1:232 
char:26
+ ...    $avSet = Get-AzAvailabilitySet -Name $availabilitysetName -Resourc ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAvailabilitySet], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureAvailabilitySetCommand
 

20220308_141933[ERROR]-Exception processing item
20220308_141933[ERROR]-Exception calling "Invoke" with "3" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 

After some research into what was going wrong, it seems that if the Availability Set you want any group of VMs to be assigned to upon initiating replication is in a different sub (i.e. the TARGET SUB) than the AzMigrate Sub (i.e. - AZMIGRATEPROJECT_SUBSCRIPTION_ID) - the AzMigrate-Start-Replication.ps1 script does not change context to the target sub and hence fails as it cannot find the Resource Group that the AS lives in so that it can grab the AS's resource ID.

I added **these two lines** to the "# Get the Availability Set" section of this script so that it will switch context to the appropriate sub and then be able to grab the AS's resource ID and then it ran properly:

**Set-AzContext -Subscription $targetSubscriptionID**
**Set-AzContext -Subscription $azMigProjSubscriptionID**

            else {
                #Get the availability set
                **Set-AzContext -Subscription $targetSubscriptionID**
                $avSet = Get-AzAvailabilitySet -Name $availabilitysetName -ResourceGroupName $targetResourceGroup
                if (-not $avSet){
                    $processor.Logger.LogTrace("AVAILABILITY Set could not be retrieved for: '$($sourceMachineName)'")
                    $reportItem.AdditionalInformation = "AVAILABILITY Set could not be retrieved for: '$($sourceMachineName)'"
                    return
                }
                else {
                    $params.Add("TargetAvailabilitySet", $avSet.Id)
                    **Set-AzContext -Subscription $azMigProjSubscriptionID**
                }
            }

This could probably use some more in depth error checking or logic built around it as this may not ALWAYS be the case and the AS *could* live in the same sub as the AzMigrate project/appliance does.  BUT, if the AS does NOT live in the same sub as the AzMigrate appliance/project - then this script will fail without it changing context to the proper Target sub to get the resource ID of the AS so it can assign the VMs to them upon initiating replication...

**Comment by rahug1190** [comment]
@mikefrobbins This is a bug in the underlying PowerShell module and not the script. The updated PowerShell module will be released by early August. In the meantime, please use Az.Migrate Powershell module 1.1.0 in the meantime and that should resolve the issue.

**Comment by mikefrobbins** [comment]
Closing this issue since there is no problem with the script per @rahug1190's comment.
