### ISSUE TITLE
AzMig_Dependencies.psm1 Error - Could Not Resolve <*****>.blob.core.windows.net

### ISSUE THREAD

**Issue by pavithrabairavan** [Azure/azure-docs-powershell-samples#385]
Hi Team,

Thank you for the script. I am able to get the list of VMs in Azure migrate project with its status of data dependency collection. However when I try to run: Get-AzMigDependenciesAgentless, i am getting a error stating that <>.blob.core.windows.net could not be resolved.

![image](https://user-images.githubusercontent.com/108405565/230596724-66479b25-fa91-45e8-9918-f382a82b7db3.png)

Am i missing something here?

Thanks!

**Comment by mikefrobbins** [comment]
@pavithrabairavan Thank you for reporting this issue. I've reached out to the service team responsible for that code and will follow-up once I hear back from them.

**Comment by danielinjesus** [comment]
Hi, I want to visualize multiple (about 500) servers altogether using agentless dependency discovery and have a few queries. 

1. For agentless dependency discovery, no installation is needed. 
https://learn.microsoft.com/en-us/azure/migrate/concepts-dependency-visualization#compare-agentless-and-agent-based

And then, why ReadMe docs says that "Ensure that VMware Tools (later than 10.2) is installed on each VM you want to analyze." 
https://github.com/Azure/azure-docs-powershell-samples/blob/master/azure-migrate/dependencies-at-scale/README.md#pre-requisites 

2. Is it only applicable to VMware servers?
https://github.com/Azure/azure-docs-powershell-samples/blob/master/azure-migrate/dependencies-at-scale/README.md#overview
![image](https://user-images.githubusercontent.com/42823007/231938676-bbdedb23-bb7f-46cd-8cd5-6fcaef9a9e34.png)

3. Is the extracted data using PowerShell the same with this data?
![image](https://user-images.githubusercontent.com/42823007/231938523-303a7abe-ce21-40c0-a4f7-5a7935ae4c7c.png)

Thank you.

**Comment by mikefrobbins** [comment]
@danielinjesus Please open a new issue as your question appears to be off topic from this issue.

**Comment by mikefrobbins** [comment]
@pavithrabairavan The product team couldn’t reproduce this issue. Please let us know if you are still experiencing this issue and provide details such as the fabric , type-of-cloud , and prerequisite commands that were run.

**Comment by mikefrobbins** [comment]
@pavithrabairavan This issue is being closed since we have not received a response. Feel free to respond with the requested information if you are still experiencing the problem reported in this issue, and we'll reopen it.
