### ISSUE TITLE
Visualization of Multiple VM Dependencies Agentlessly

### ISSUE THREAD

**Issue by danielinjesus** [Azure/azure-docs-powershell-samples#387]
Hi, I want to visualize multiple (about 500) servers altogether using agentless dependency discovery and have a few queries. 

1. For agentless dependency discovery, no installation is needed. 
https://learn.microsoft.com/en-us/azure/migrate/concepts-dependency-visualization#compare-agentless-and-agent-based

And then, why ReadMe docs says that "Ensure that VMware Tools (later than 10.2) is installed on each VM you want to analyze." 
https://github.com/Azure/azure-docs-powershell-samples/blob/master/azure-migrate/dependencies-at-scale/README.md#pre-requisites 

2. Is it only applicable to VMware servers?
https://github.com/Azure/azure-docs-powershell-samples/blob/master/azure-migrate/dependencies-at-scale/README.md#overview
![image](https://user-images.githubusercontent.com/42823007/231938676-bbdedb23-bb7f-46cd-8cd5-6fcaef9a9e34.png)

3. Is the extracted data using PowerShell the same with this data?
![image](https://user-images.githubusercontent.com/42823007/231938523-303a7abe-ce21-40c0-a4f7-5a7935ae4c7c.png)

Thank you.

**Comment by mikefrobbins** [comment]
@danielinjesus Thank you for reporting this issue. I've reached out to the service team responsible for that code and will follow-up once I hear back from them.

**Comment by Vikram1988** [comment]
@danielinjesus there are no agents installed when performing agentless dependency analysis from VMware VMs but to remotely pull the netstat data, we use the vSphere APIs that need VMware tools to be installed on each of the target servers. This is only needed for VMware VMs when you are using the Azure Migrate appliance for VMware. In case you want to treat these VMs as physical servers and use the physical Azure Migrate appliance for Physical, then we directly connect to the target servers without using the vSphere APIs and hence VMware Tools are not required. To your second question, you can either use Portal UI or PS commands to export the dependency analysis data- it would be the same output Hope this clarifies your doubt.
