### ISSUE TITLE
API endpoint in Set-AzMigDependencyMappingAgentless function does not work for Hyper-V

### ISSUE THREAD

**Issue by RylandDeGregory** [Azure/azure-docs-powershell-samples#391]
The API endpoint used to enable/disable dependency mapping for discovered VMs does not work for Hyper-V machines. The endpoint accepts the request without error, creates and operation, and successfully completes the operation without error. However, the property is not updated on any of the VMs that were submitted to the endpoint.

After inspecting the request that the Azure Portal uses to enable dependency mapping for Hyper-V VMs, I noticed that the portal is using a different endpoint than the one defined in the PowerShell module. This is an un-published endpoint (not sure why), but it correctly enables dependency mapping at scale for Hyper-V VMs.

The endpoint used in the PowerShell module, that works for VMware VMs, is:
`https://management.azure.com/subscriptions/<subscriptionid>/resourceGroups/<resource group>/providers/Microsoft.OffAzure/VMwareSites/<site name>/UpdateProperties?api-version=2020-01-01`.
It expects a body object formatted like this:
```json
{
  "machines": [
    {
      "machineArmId": "/subscriptions/<subscriptionid>/resourceGroups/<resource group>/providers/Microsoft.OffAzure/HyperVSites/<site name>/machines/<machine guid>",
      "dependencyMapping": "Enabled"
    }
  ]
}
```

The unpublished endpoint used in the Portal, that works for Hyper-V VMs, is:
`https://management.azure.com/subscriptions/<subscriptionid>/resourceGroups/<resource group>/providers/Microsoft.OffAzure/HyperVSites/<site name>/UpdateDependencyMapStatus?api-version=2020-08-01-preview`.
It expects a body object formatted like this:
```json
{
  "machines": [
    {
      "machineId": "/subscriptions/<subscriptionid>/resourceGroups/<resource group>/providers/Microsoft.OffAzure/HyperVSites/<site name>/machines/<machine guid>",
      "isDependencyMapToBeEnabled": true
    }
  ]
}
```

Can the PowerShell module be updated to include this endpoint that works for Hyper-V machines? Alternatively, are PRs accepted for this repository?

**Comment by mikefrobbins** [comment]
@RylandDeGregory Thank you for reporting this issue. I've reached out to the service team responsible for that code and will follow-up once I hear back from them.

**Comment by mikefrobbins** [comment]
@RylandDeGregory I've sent a follow-up message to the service team who owns the sample code and is responsible for maintaining it. Is there a specific article on Microsoft Learn you're following that requires this sample?

All code in this repository is non-production samples used in our official Azure PowerShell documentation and is designed to be used by our customers for learning and experimentation purposes.

**Comment by mikefrobbins** [comment]
@RylandDeGregory Per the product team, currently, the script serves only for VMware fabric. Yes, PRs are accepted for this repository.

**Comment by mikefrobbins** [comment]
@RylandDeGregory This issue is being closed since the sample script is working as designed by the product team. The product team is aware of this request and may consider adding other fabrics to the sample script at some point.
