### ISSUE TITLE
Is it possible to add -ApplianceName Parameter when using Get-AzMigDiscoveredVMwareVMs

### ISSUE THREAD

**Issue by jwells38654** [Azure/azure-docs-powershell-samples#392]
Is it possible to add -ApplianceName as a parameter when using Get-AzMigDiscoveredVMwareVMs ?  Scenario When having multiple Azure Migrate appliances registered to a single project all discovered VMs are exported into one output file which has duplicates server name entries.

**Comment by mikefrobbins** [comment]
@jwells38654 Thank you for reporting this issue. I've reached out to the service team responsible for that code and will follow-up once I hear back from them.

**Comment by jwells38654** [comment]
Hi Mike, is there any update?

**Comment by shivamverma-ms** [comment]
Hi, @Vikram1988 / @mikefrobbins ,

For addressing an ICM incident, I made some changes in the ps automation scripts for scale users migration and added an extra parameter -ApplianceName to the Get-DiscoveredServer Call like this:
"""
Get-AzMigrateDiscoveredServer -ApplianceName $AzMigrateApplianceName `
                                                        -ProjectName $AzMigrateProjectName `
                                                        -ResourceGroupName $AzMigrateResourceGroupName `
                                                        -DisplayName $machineName
"""

And this is working, I have also raised a PR regarding this as well. In case you needed it to be validated, i have already tried and it's working i.e giving out the discovered vm's by ApplianceName. Hope this helps!

**Comment by Vikram1988** [comment]
Thanks @***@***.***> for taking this up.

Looping in @***@***.***> who has taken over the Agentless dependency analysis area and would track any changes with the PowerShell module henceforth.
Regards,
Vikram Bansal
Senior Product Manager | Azure Migrate

**Comment by jwells38654** [comment]
Hello, thanks for the update!  However, my original request was to add -ApplianceName parameter to the Get-AzMigDiscoveredVMwareVMs powershell command for enabling dependency analysis at scale.  This is documented for enabling dependency analysis at scale via command line (see link below).  Is this possible? 

[https://github.com/Azure/azure-docs-powershell-samples/tree/master/azure-migrate/dependencies-at-scale#dependency-analysis-using-powershell-in-azure-migrate](Dependency Analysis at scale)

**Comment by jwells38654** [comment]
Hello, thanks for the update!  However, my original request was to add -ApplianceName parameter to the Get-AzMigDiscoveredVMwareVMs powershell command for enabling dependency analysis at scale.  This is documented for enabling dependency analysis at scale via command line (see link below).  Is this possible? 

[](url)
[https://github.com/Azure/azure-docs-powershell-samples/tree/master/azure-migrate/dependencies-at-scale#dependency-analysis-using-powershell-in-azure-migrate](Dependency Analysis at scale)

**Comment by mikefrobbins** [comment]
@jwells38654 Please be aware that this repo does not contain production code or tools. All code in this repository is non-production samples used in Microsoft's official Azure PowerShell documentation and is designed to be used by our customers for learning and experimentation purposes.
