### ISSUE TITLE
InvalidHttpRequestPath

### ISSUE THREAD

**Issue by OrionWithrow-OHIT** [Azure/azure-docs-powershell-samples#395]
Trying to export dependencies to Power BI. This worked perfectly yesterday, today I am receiving an error InvalidHttpRequestPath. I downloaded the current version of AzMig_Dependencies.psm and I have tested it in Powershell5.x, 7.3, and 7.4 preview all with the same error.
<img width="1624" alt="Screenshot 2023-06-13 at 1 24 06 PM" src="https://github.com/Azure/azure-docs-powershell-samples/assets/132500090/a2d274e9-76f3-4dc0-8784-e27063df01f6">

**Comment by sdevathi-github** [comment]
can you give the command with verbose option and can you check the route to appliance is broken?

**Comment by OrionWithrow-OHIT** [comment]
I figured it out, there is a line in the module that throws this error if you try to run the script against an appliance for Physical servers.

**Comment by OrionWithrow-OHIT** [comment]
Thanks for your help
